spring.application.name=SpringStudy
spring.config.import=optional:application-secret.properties

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database=postgresql

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# Hibernate? DB ??? ?? ???? ?? ??
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect